
spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071

logging:
  level:
    web: debug



resilience4j.circuitbreaker:
  instances:
    licensingService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 50

